#!/bin/bash

which go

echo "Output program name: ${INPUT_NAME}"

pwd

go get github.com/fsnotify/fsnotify@v1.4.7

export GOOS="windows"
export GOARCH="amd64"

go build -o "dist/${INPUT_NAME}-${GOOS}-${GOARCH}.exe"

ls dist